name: Vless Auto Update

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: python parser.py


      - name: Push configs to GitVerse
        env:
          GV_USER: ${{ secrets.GV_USER }}
          GV_TOKEN: ${{ secrets.GV_TOKEN }}
        run: |
          git clone https://${GV_USER}:${GV_TOKEN}@gitverse.ru/mirgittech/miamy.git gitverse

          cp conf.txt gitverse/conf.txt

          cd gitverse

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add configs.txt
          git commit -m "Auto update configs $(date)" || exit 0
          git push origin master
