name: Vless Auto Update

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: python parser.py

      - name: Push configs to GitVerse
        env:
          GV_TOKEN: ${{ secrets.GV_TOKEN }}
        run: |
          set -e

          git clone https://${GV_TOKEN}@gitverse.ru/mirgittech/mia.git gitverse

          cp configs.txt gitverse/configs.txt

          cd gitverse

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add configs.txt

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Auto update configs $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push origin master
